apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
spec:
  replicas: {{ if .Values.autoscaling.enabled }}
     {{ .Values.autoscaling.minReplicas }}
   {{ else }}
     {{ .Values.replicaCount | default 2 }}
   {{ end }}
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
    spec:
      containers:
        - name: {{ .Values.service.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: APP_NAME
              value: "my-gatekeeper-k8s"
            - name: PORT
              value: "{{ .Values.service.port }}"
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: {{ .Values.service.port }}
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: {{ .Values.service.port }}
            initialDelaySeconds: 1
            periodSeconds: 5
          resources:
            requests:
              cpu:    {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu:    {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}