apiVersion: v2
name: playground-chart
description: Unified chart for Envoy, Auth, and Backend services
version: 0.1.0
appVersion: "1.0.0"
type: application

dependencies:
  - name: auth
    version: "0.1.0"
    repository: "file://./charts/auth"
    condition: auth.enabled
  - name: backend
    version: "0.1.0"
    repository: "file://./charts/backend"
    condition: backend.enabled
  - name: envoy
    version: "0.1.0"
    repository: "file://./charts/envoy"
    condition: envoy.enabled