apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.auth.service.name }}
spec:
  selector:
    app: auth
  ports:
    - name: http
      port: {{ .Values.auth.service.port }}
      targetPort: {{ .Values.auth.service.port }}
    - name: grpc
      port: {{ .Values.auth.service.grpcPort }}
      targetPort: {{ .Values.auth.service.grpcPort }}